AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for Kiro API'

Resources:
  KiroTaskQueue:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kiro-task-queue
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-createdAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: kiro-api

  KiroSessions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kiro-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      Tags:
        - Key: Project
          Value: kiro-api

Outputs:
  TaskQueueTableName:
    Description: Task queue table name
    Value: !Ref KiroTaskQueue
    Export:
      Name: KiroTaskQueueTable

  SessionsTableName:
    Description: Sessions table name
    Value: !Ref KiroSessions
    Export:
      Name: KiroSessionsTable
